version: "1.0"
info:
  model: int-scaffold
packages:
- name: Sergh2208devProject
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: upperfspackage
  gitServerName: RAHS_IBMBitbucket
  gitUrl: https://bitbucket.org/testartiibm
  gitUsername: rahulsingh68
  gitBranch: master
